[package]
name = "wgpu_renderer_cli"
version = "0.1.0"
edition = "2018"

[dependencies]
cgmath = "0.18"
clap = "2.33.3"
image = "0.23"
mesh = { path = "../mesh" }
wgpu_renderer = { path = "../wgpu_renderer" }
